### ISSUE TITLE
ClerkKit 1.2.9 fails to build with Swift 6.4 / Xcode 27 region-based isolation checker error

### ISSUE THREAD

**Issue by davidcruzcs** [clerk/clerk-ios#513]
## Summary

`ClerkKit` fails to build with Xcode 27 / Swift 6.4 due to a Swift compiler region-based isolation checker error.

The same project builds successfully with Xcode 26.6 / Swift 6.3.3 using the same source code and the same resolved ClerkKit version.

This appears to be a Swift compiler/toolchain compatibility issue surfaced by `ClerkKit`, specifically in `PasskeyHelper.swift`.

## Environment

| Item | Value |
| --- | --- |
| Clerk package | `clerk-ios` |
| ClerkKit version | `1.2.9` |
| Clerk revision | `7948819563b82f29ae7505f79e45ae843ab72228` |
| Clerk tag | `1.2.9` |
| Failing Xcode | `Xcode 27.0` |
| Failing Xcode build | `27A5209h` |
| Failing Swift | `Apple Swift 6.4`, `swiftlang-6.4.0.23.5` |
| Failing SDK | `iPhoneOS27.0.sdk` |
| Host macOS | `macOS 26.5.1`, build `25F80` |
| Platform | iOS |
| Package manager | Swift Package Manager |
| Working Xcode | `Xcode 26.6`, build `17F113` |
| Working Swift | `Apple Swift 6.3.3`, `swiftlang-6.3.3.1.3` |

## Package Configuration

My package depends on Clerk like this:

```swift
.package(url: "https://github.com/clerk/clerk-ios", from: "1.2.9")
```

## Error

The build fails while compiling:

```text
Sources/ClerkKit/Helpers/PasskeyHelper.swift
```

Diagnostic:

```text
PasskeyHelper.swift:97:22: error: pattern that the region-based isolation checker does not understand how to check. Please file a bug
```

## Failing Code Area

The failing code is in `PasskeyHelper.performAuthorization(...)`:

```swift
@MainActor
private func performAuthorization(
  requests: [ASAuthorizationRequest],
  start: @escaping @MainActor (ASAuthorizationController) -> Void
) async throws -> ASAuthorization {
  try Task.checkCancellation()
  Self.cancelCurrentAuthorization()
  let helperID = ObjectIdentifier(self)

  return try await withTaskCancellationHandler {
    try Task.checkCancellation()
    return try await withCheckedThrowingContinuation { continuation in
      self.continuation = continuation
      Self.activeHelper = self

      let authController = ASAuthorizationController(authorizationRequests: requests)
      authController.delegate = self
      authController.presentationContextProvider = self
      Self.controller = authController

      start(authController)
    }
  } onCancel: {
    Task { @MainActor in
      Self.cancelAuthorization(for: helperID)
    }
  }
}
```

## Relevant Compiler Context

The failing ClerkKit compile uses:

```text
-swift-version 6
-enable-upcoming-feature StrictConcurrency
-sdk /Applications/Xcode-beta.app/.../iPhoneOS27.0.sdk
-target arm64-apple-ios17.0
-user-module-version 1.2.9
-target-sdk-version 27.0
-target-sdk-name iphoneos27.0
```

## Expected Behavior

`ClerkKit` should build successfully with Xcode 27 / Swift 6.4, or there should be a documented workaround.

## Actual Behavior

The build fails during `ClerkKit` compilation with:

```text
pattern that the region-based isolation checker does not understand how to check. Please file a bug
```

## Reproduction

1. Use `clerk-ios` `1.2.9`.
2. Build with Xcode 27.0 build `27A5209h`.
3. Observe the build failure in:

```text
Sources/ClerkKit/Helpers/PasskeyHelper.swift:97:22
```

4. Build the same project with Xcode 26.6.
5. The project builds successfully.

## Question

Is there a recommended source-level workaround for this in ClerkKit, or should this be reported directly to the Swift compiler project as a Swift 6.4 region-based isolation checker bug?

**Comment by seanperez29** [comment]
This will be resolved shortly with this PR https://github.com/clerk/clerk-ios/pull/514. Thanks!
